networks:
  default:
    name: nextcloud-network

services:
  app:
    container_name: nextcloud
    depends_on:
      - database
      - cache
    environment:
      - NEXTCLOUD_ADMIN_USER=${ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - NEXTCLOUD_TRUSTED_DOMAINS=cloud.christophthiel.com
      - OVERWRITEPROTOCOL=https
      - POSTGRES_HOST=database
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=nextcloud
      - REDIS_HOST=cache
      - REDIS_HOST_PORT=6379
      - REDIS_HOST_PASSWORD=${REDIS_PASSWORD}
    image: nextcloud
    ports:
      - 8080:80
    restart: always
    volumes:
      - nextcloud:/var/www/html
      - /storage/nextcloud:/var/www/html/data
      - /opt/docker/nextcloud/config:/var/www/html/config

  database:
    container_name: nextcloud-postgres
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    image: postgres
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data

  cache:
    command: redis-server --requirepass ${REDIS_PASSWORD}
    container_name: nextcloud-redis
    image: redis
    restart: always
    volumes:
     - redis:/data

  onlyoffice:
    container_name: nextcloud-onlyoffice
    environment:
     - JWT_SECRET=${JWT_SECRET}
    image: onlyoffice/documentserver
    ports:
     - 8008:80
    restart: always


volumes:
  nextcloud:
    name: "nextcloud"
  postgres:
    name: "nextcloud-postgres"
  redis:
    name: "nextcloud-redis"